// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using myshoppinglist_api.Data;

#nullable disable

namespace myshoppinglist_api.Data.Migrations
{
    [DbContext(typeof(MyShoppingListDbContext))]
    partial class MyShoppingListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("myshoppinglist_api.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("GTIN")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PackQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PackSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PackUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GTIN");

                    b.HasIndex("Brand", "ManufacturerPartNumber", "ModelNumber");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_PackQuantity", "\"PackQuantity\" IS NULL OR \"PackQuantity\" > 0");

                            t.HasCheckConstraint("CK_Products_PackSize", "\"PackSize\" IS NULL OR \"PackSize\" > 0");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ProductImportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClaimToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalisedSourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressStage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.Property<long>("ShoppingListId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShoppingListProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceShopId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("ShoppingListId", "Status");

                    b.HasIndex("ShoppingListId", "UserAccountId");

                    b.HasIndex("Status", "LeaseExpiresDate");

                    b.HasIndex("ShoppingListProductId", "ShoppingListId", "ProductId");

                    b.HasIndex("Status", "NextAttemptDate", "CreatedDate");

                    b.ToTable("ProductImportJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImportJobs_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_ProductImportJobs_Claim", "(\"Status\" = 'Processing' AND \"ClaimToken\" IS NOT NULL AND \"LeaseExpiresDate\" IS NOT NULL) OR (\"Status\" <> 'Processing' AND \"ClaimToken\" IS NULL AND \"LeaseExpiresDate\" IS NULL)");

                            t.HasCheckConstraint("CK_ProductImportJobs_ListItem", "\"ShoppingListProductId\" IS NULL OR \"ProductId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_ProductImportJobs_Quantity", "\"RequestedQuantity\" > 0");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ProductImportRetailerResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsFromCache")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("MatchType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("ProductImportJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("ProductImportJobId", "ShopId")
                        .IsUnique();

                    b.HasIndex("ShopProductId", "ShopId");

                    b.ToTable("ProductImportRetailerResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImportRetailerResults_MatchConfidence", "\"MatchConfidence\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("Shops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "coles",
                            CreatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "coles.com.au",
                            IsActive = true,
                            Name = "Coles",
                            UpdatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.coles.com.au"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "woolworths",
                            CreatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "woolworths.com.au",
                            IsActive = true,
                            Name = "Woolworths",
                            UpdatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.woolworths.com.au"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "aldi",
                            CreatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "aldi.com.au",
                            IsActive = true,
                            Name = "ALDI",
                            UpdatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.aldi.com.au"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "iga",
                            CreatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "iga.com.au",
                            IsActive = true,
                            Name = "IGA",
                            UpdatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.iga.com.au"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "foodland",
                            CreatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "foodlandsa.com.au",
                            IsActive = true,
                            Name = "Foodland",
                            UpdatedDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.foodlandsa.com.au"
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Address2")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StoreCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "StoreCode")
                        .IsUnique()
                        .HasFilter("\"StoreCode\" IS NOT NULL");

                    b.ToTable("ShopLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShopLocations_Latitude", "\"Latitude\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_ShopLocations_Longitude", "\"Longitude\" BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DescriptionAtShop")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("FirstFoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GTIN")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NameAtShop")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShopProductCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShopSku")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "ShopId");

                    b.HasIndex("ShopId", "ShopProductCode")
                        .IsUnique()
                        .HasFilter("\"ShopProductCode\" IS NOT NULL");

                    b.ToTable("ShopProducts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShopProducts_MatchConfidence", "\"MatchConfidence\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProductPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool?>("InStock")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NormalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PriceScope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("ShopLocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SpecialDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("SpecialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SpecialStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopLocationId");

                    b.HasIndex("ShopProductId", "PriceScope", "Currency")
                        .IsUnique()
                        .HasFilter("\"ShopLocationId\" IS NULL");

                    b.HasIndex("ShopProductId", "ShopLocationId", "PriceScope", "Currency")
                        .IsUnique()
                        .HasFilter("\"ShopLocationId\" IS NOT NULL");

                    b.ToTable("ShopProductPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShopProductPrices_Price", "\"Price\" >= 0 AND (\"NormalPrice\" IS NULL OR \"NormalPrice\" >= 0) AND (\"UnitPrice\" IS NULL OR \"UnitPrice\" >= 0)");

                            t.HasCheckConstraint("CK_ShopProductPrices_SpecialDates", "\"SpecialStartDate\" IS NULL OR \"SpecialEndDate\" IS NULL OR \"SpecialEndDate\" >= \"SpecialStartDate\"");

                            t.HasCheckConstraint("CK_ShopProductPrices_StoreScope", "\"PriceScope\" <> 'StoreSpecific' OR \"ShopLocationId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProductPriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("NormalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PriceScope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("ShopLocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SpecialDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("SpecialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SpecialStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ShopLocationId");

                    b.HasIndex("ShopProductId", "CheckedDate");

                    b.ToTable("ShopProductPriceHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShopProductPriceHistory_Price", "\"Price\" >= 0 AND (\"NormalPrice\" IS NULL OR \"NormalPrice\" >= 0) AND (\"UnitPrice\" IS NULL OR \"UnitPrice\" >= 0)");

                            t.HasCheckConstraint("CK_ShopProductPriceHistory_SpecialDates", "\"SpecialStartDate\" IS NULL OR \"SpecialEndDate\" IS NULL OR \"SpecialEndDate\" >= \"SpecialStartDate\"");

                            t.HasCheckConstraint("CK_ShopProductPriceHistory_StoreScope", "\"PriceScope\" <> 'StoreSpecific' OR \"ShopLocationId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShoppingList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresDate");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ShoppingLists", (string)null);
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShoppingListProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long?>("PreferredShopId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("ShoppingListId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PreferredShopId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingListId", "ProductId")
                        .IsUnique();

                    b.ToTable("ShoppingListProducts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShoppingListProducts_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("IsTrial", "ExpiresDate");

                    b.ToTable("UserAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_Credentials", "(\"IsTrial\" AND \"ExpiresDate\" IS NOT NULL AND \"Email\" IS NULL AND \"PasswordHash\" IS NULL AND \"PasswordSalt\" IS NULL) OR (NOT \"IsTrial\" AND \"Email\" IS NOT NULL AND \"PasswordHash\" IS NOT NULL AND \"PasswordSalt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("myshoppinglist_api.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresDate");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ProductImportJob", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("myshoppinglist_api.Models.Shop", "SourceShop")
                        .WithMany()
                        .HasForeignKey("SourceShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("myshoppinglist_api.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.ShoppingList", "ShoppingList")
                        .WithMany()
                        .HasForeignKey("ShoppingListId", "UserAccountId")
                        .HasPrincipalKey("Id", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.ShoppingListProduct", "ShoppingListProduct")
                        .WithMany()
                        .HasForeignKey("ShoppingListProductId", "ShoppingListId", "ProductId")
                        .HasPrincipalKey("Id", "ShoppingListId", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");

                    b.Navigation("ShoppingListProduct");

                    b.Navigation("SourceShop");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ProductImportRetailerResult", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.ProductImportJob", "ProductImportJob")
                        .WithMany()
                        .HasForeignKey("ProductImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.ShopProduct", "ShopProduct")
                        .WithMany()
                        .HasForeignKey("ShopProductId", "ShopId")
                        .HasPrincipalKey("Id", "ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductImportJob");

                    b.Navigation("Shop");

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopLocation", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProduct", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProductPrice", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.ShopLocation", "ShopLocation")
                        .WithMany()
                        .HasForeignKey("ShopLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("myshoppinglist_api.Models.ShopProduct", "ShopProduct")
                        .WithMany()
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShopLocation");

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShopProductPriceHistory", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.ShopLocation", "ShopLocation")
                        .WithMany()
                        .HasForeignKey("ShopLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("myshoppinglist_api.Models.ShopProduct", "ShopProduct")
                        .WithMany()
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShopLocation");

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShoppingList", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.ShoppingListProduct", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.Shop", "PreferredShop")
                        .WithMany()
                        .HasForeignKey("PreferredShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("myshoppinglist_api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myshoppinglist_api.Models.ShoppingList", "ShoppingList")
                        .WithMany()
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredShop");

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("myshoppinglist_api.Models.UserSession", b =>
                {
                    b.HasOne("myshoppinglist_api.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
